server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/youniverse
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug