server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /api

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://youniverse-db.cs9djr1z57vs.ap-northeast-2.rds.amazonaws.com:3306/Youniverse?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: youniverse

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000